### ISSUE TITLE
nasztomaszow.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement#137]
kilka RSS - ów ( na głównej )

**Comment by krystian3w** [comment]
`##li > a > .icon-rss` - https://github.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement/commit/a56e0c7b249a365679b35647cd3576f1747f4069 myślę, że to rozwiąże problem z grupą 

![obraz](https://user-images.githubusercontent.com/35370833/85753645-b7d68000-b70c-11ea-8372-ec22cd8ddb0e.png) / ![obraz](https://user-images.githubusercontent.com/35370833/85753689-c15fe800-b70c-11ea-92ef-51900ba4a7bf.png)



https://github.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement/commit/cd3eee0becce439c80c0a4e4a8186e86788b84f5
