### ISSUE TITLE
Adguard metadata.json

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement#62]
https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_247_PolishRssFilters/metadata.json

?

Nazwę folderu by musieli pewnie we własnym zakresie jakoś skorygować by nie wpaść w pętle, że bot zablokował scalanie.

**Comment by AdamWr** [comment]
@krystian3w  Dobrze rozumiem, że chodzi o zmianę z `https://raw.githubusercontent.com/PolishFiltersTeam/PolishRSSFilters/master/polish_rss_filters.txt` na
`https://raw.githubusercontent.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt`?
Czy o coś innego?

**Comment by krystian3w** [comment]
Tak i może nazwę i pole opisy, jak katalog można tylko po pobraniu na PC to zostaw 160 MB ściągania.

**Comment by krystian3w** [comment]
A i niby jest angielski wulgaryzmy jak się usunie P - tego nie przewidziano.

**Comment by AdamWr** [comment]
Czyli:
`"name": "Polski Antyirytujący Dodatek Specjalny"`

`"description": "Filtry blokujące i ukrywające elementy RSS oraz resztki po ukrytych newsletterach złączonych z elementami społecznościowymi na polskojęzycznych stronach."`

`"homepage": "https://github.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement"`

```
"subscriptionUrl": "https://raw.githubusercontent.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt"
```

Tak będzie w porządku?

**Comment by krystian3w** [comment]
Tak.

**Comment by AdamWr** [comment]
Ok, dziękuję.
https://github.com/AdguardTeam/FiltersRegistry/pull/229
