### ISSUE TITLE
zachod.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement#72]
RSS ( na dole ) a i jeszcze przy okazji można tą ankiete usunąć " twoja opinia " tylko gdzie to dodać ?

**Comment by krystian3w** [comment]
Ankietę w filtrach własnych, ona nie jest "czy podoba wam się nasz wygląd strony"... ani reklamą, politykę też nie każdy lubi wycinać.
